### PR TITLE
Docs/adding afs instructions

### PR DESCRIPTION
**Pull request by lawrenceleejr**
Adding an a set of instructions that I got to work on lxplus by jumping through some hoops. Wasn't the most fun, but it'll be better than killing my laptop's battery all the time!

### CODE REVIEW

**Comment by mattleblanc** [comment]
Following these instructions on the two tier3's that I have access to fails to result in a working setup on either one ... 

```
(ROOT)login:Optimization mleblanc$ pip install PyYAML==3.11
Downloading/unpacking PyYAML==3.11
  Downloading PyYAML-3.11.tar.gz (248kB): 248kB downloaded
  Running setup.py egg_info for package PyYAML
    /home/mleblanc/Optimization/ROOT/build/PyYAML/setup.py:11: DeprecationWarning: Parameters to load are deprecated.  Call .resolve and .require separately.
      support, capable extension API, and sensible error messages.  PyYAML
Installing collected packages: PyYAML
  Running setup.py install for PyYAML
    checking if libyaml is compilable
    gcc -pthread -fno-strict-aliasing -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I/usr/include/python2.6 -c build/temp.linux-x86_64-2.6/check_libyaml.c -o build/temp.linux-x86_64-2.6/check_libyaml.o
    build/temp.linux-x86_64-2.6/check_libyaml.c:2:18: fatal error: yaml.h: No such file or directory
     #include <yaml.h>
                      ^
    compilation terminated.

    libyaml is not found or a compiler error: forcing --without-libyaml
    (if libyaml is installed correctly, you may need to
     specify the option --include-dirs or uncomment and
     modify the parameter include_dirs in setup.cfg)
  Could not find .egg-info directory in install record for PyYAML==3.11
Successfully installed PyYAML
Cleaning up...
```

etc. for other packages listed in `requirements.txt`

**Comment by mattleblanc** [comment]
Following these instructions on US Connect seems to give some functionality, but also some peculiar errors ...

```
(ROOT)login:Optimization mleblanc$ python optimize.py -h
input_line_1:1:10: fatal error: file '/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/new' modified since it was first processed
#include <new>
         ^
input_line_3:38:10: fatal error: file '/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/string' modified since it was first processed
#include <string>
         ^
usage: optimize.py [-h] [-a] {generate,cut,optimize,hash} ...

Author: Giordon Stark. v.v3.2-198-g22b73bd

positional arguments:
  {generate,cut,optimize,hash}
                              actions available
    generate                  Write supercuts template
    cut                       Apply the cuts
    optimize                  Calculate significances for a series of computed
                              cuts
    hash                      Translate hash to cut

optional arguments:
  -h, --help                  show this help message and exit
  -a, --allhelp               show this help message and all subcommand help
                              messages and exit

This is the top-level. You have no power here.
```

@kratsg may have insight?

**Comment by kratsg** [comment]
Rebase this to remove the `merge pull request` and then rebase your changes on top of master instead. I dislike merge :)

**Comment by kratsg** [comment]
> Following these instructions on US Connect seems to give some functionality, but also some peculiar errors ...

I'll ask Lincoln what's up.

**Comment by mattleblanc** [comment]
Follow-up from before, using the same setup that was producing errors, if I go from a fresh shell and

```
setupATLAS
lsetup root
source ROOT/bin/activate
python optimize.py -h
```

things seem to work without errors, at least on US Connect.

At TRIUMF, vEnv's aren't available out of the box, so I haven't tested there yet.

**Comment by kratsg** [comment]
Hi all, I can't seem to get this working. I must be missing something else in my environment?

**Comment by mattleblanc** [comment]
```
(ROOT)login:Optimization mleblanc$ which root
alias root='root -l'
	/cvmfs/atlas.cern.ch/repo/ATLASLocalRootBase/x86_64/root/6.04.14-x86_64-slc6-gcc49-opt/bin/root
```

```
(ROOT)login:Optimization mleblanc$ which python
~/Optimization/ROOT/bin/python
```

You've gotta be very careful about which python you're pointing at during the installation -- Larry, is it possible that there's a mixup in your instructions somewhere?

**Comment by kratsg** [comment]
Hi all, I know this is super late to the game at this point. But I've added instructions that work(!!!!!) here: https://github.com/kratsg/optimization#on-a-cvmfs-enabled-machine . So this PR is being closed. Sorries Larry.

**Pull request closed without merging**
